"""
tests/publishers/test_blog.py
==============================
Unit tests for agent/publishers/blog.py.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from agent.publishers.base import ArticleSummary, ContentPackage
from agent.publishers.blog import BlogPublisher


@pytest.fixture
def package() -> ContentPackage:
    """A minimal ContentPackage for blog publisher tests."""
    return ContentPackage(
        topic="AI Takes Over the World (Not Really)",
        digest="This week's tech news covers AI, cloud, and open-source advances.",
        articles=[
            ArticleSummary(
                title="AWS Launches Something Cool",
                url="https://aws.amazon.com/blog/something-cool",
                summary="AWS announced a new service that does things.",
                relevance_score=5,
                source="AWS Blog",
            ),
            ArticleSummary(
                title="Python 4.0 Released",
                url="https://python.org/news/python-4",
                summary="Python 4.0 ships with major performance improvements.",
                relevance_score=4,
                source="Python.org",
            ),
        ],
        keywords=["aws", "python", "ai", "cloud"],
        raw_post="This is the raw post body generated by Bedrock.",
    )


class TestBlogPublisherFormatContent:
    """Tests for BlogPublisher.format_content()."""

    def test_returns_string(self, package: ContentPackage, tmp_path: Path) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        result = publisher.format_content(package)
        assert isinstance(result, str)

    def test_contains_topic_in_front_matter(self, package: ContentPackage, tmp_path: Path) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        result = publisher.format_content(package)
        assert package.topic in result

    def test_contains_keywords_in_front_matter(
        self, package: ContentPackage, tmp_path: Path
    ) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        result = publisher.format_content(package)
        for kw in package.keywords:
            assert kw in result

    def test_contains_article_urls(self, package: ContentPackage, tmp_path: Path) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        result = publisher.format_content(package)
        for article in package.articles:
            assert article.url in result

    def test_contains_raw_post(self, package: ContentPackage, tmp_path: Path) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        result = publisher.format_content(package)
        assert package.raw_post in result

    def test_has_yaml_front_matter(self, package: ContentPackage, tmp_path: Path) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        result = publisher.format_content(package)
        assert result.startswith("---")
        assert "draft: false" in result


class TestBlogPublisherPublish:
    """Tests for BlogPublisher.publish()."""

    def test_publish_creates_file(self, package: ContentPackage, tmp_path: Path) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        content = publisher.format_content(package)
        result = publisher.publish(content)
        assert result.success is True
        assert result.platform == "blog"

    def test_publish_file_exists_on_disk(self, package: ContentPackage, tmp_path: Path) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        content = publisher.format_content(package)
        result = publisher.publish(content)
        assert result.url is not None
        assert Path(result.url).exists()

    def test_publish_file_contains_content(self, package: ContentPackage, tmp_path: Path) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        content = publisher.format_content(package)
        result = publisher.publish(content)
        assert result.url is not None
        written = Path(result.url).read_text(encoding="utf-8")
        assert package.topic in written

    def test_publish_creates_output_dir_if_missing(
        self, package: ContentPackage, tmp_path: Path
    ) -> None:
        nested = tmp_path / "deep" / "nested" / "dir"
        publisher = BlogPublisher(output_dir=str(nested))
        content = publisher.format_content(package)
        result = publisher.publish(content)
        assert result.success is True
        assert nested.exists()

    def test_publish_result_has_no_error_on_success(
        self, package: ContentPackage, tmp_path: Path
    ) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        content = publisher.format_content(package)
        result = publisher.publish(content)
        assert result.error is None


class TestBlogPublisherRun:
    """Tests for the inherited BasePublisher.run() orchestration."""

    def test_run_returns_success_result(self, package: ContentPackage, tmp_path: Path) -> None:
        publisher = BlogPublisher(output_dir=str(tmp_path))
        result = publisher.run(package)
        assert result.success is True
        assert result.platform == "blog"
